import NetCatIntentsdata from '../Build/IntentsBuilder.js';

NetCatIntentsdata.then(PromiseResolve => {
    const NetCatIntents = {
    GUILDS: NetCatIntentsdata.GUILDS,
    GUILD_MEMBERS: NetCatIntentsdata.GUILD_MEMBERS,
    GUILD_MODERATION: NetCatIntentsdata.GUILD_MODERATION,
    GUILD_EMOJIS_AND_STICKERS: NetCatIntentsdata.GUILD_EMOJIS_AND_STICKERS,
    GUILD_INTEGRATIONS: NetCatIntentsdata.GUILD_INTEGRATIONS,
    GUILD_WEBHOOKS: NetCatIntentsdata.GUILD_WEBHOOKS,
    GUILD_INVITES: NetCatIntentsdata.GUILD_INVITES,
    GUILD_VOICE_STATES: NetCatIntentsdata.GUILD_VOICE_STATES,
    GUILD_PRESENCES: NetCatIntentsdata.GUILD_PRESENCES,
    GUILD_MESSAGES: NetCatIntentsdata.GUILD_MESSAGES,
    GUILD_MESSAGE_REACTIONS: NetCatIntentsdata.GUILD_MESSAGE_REACTIONS,
    GUILD_MESSAGE_TYPING: NetCatIntentsdata.GUILD_MESSAGE_TYPING,
    DIRECT_MESSAGES: NetCatIntentsdata.DIRECT_MESSAGES,
    DIRECT_MESSAGE_REACTIONS: NetCatIntentsdata.DIRECT_MESSAGE_REACTIONS,
    DIRECT_MESSAGE_TYPING: NetCatIntentsdata.DIRECT_MESSAGE_TYPING,
    MESSAGE_CONTENT: NetCatIntentsdata.MESSAGE_CONTENT,
    GUILD_SCHEDULED_EVENTS: NetCatIntentsdata.GUILD_SCHEDULED_EVENTS,
    AUTO_MODERATION_CONFIGURATION: NetCatIntentsdata.AUTO_MODERATION_CONFIGURATION,
    AUTO_MODERATION_EXECUTION: NetCatIntentsdata.AUTO_MODERATION_EXECUTION
}

module.exports = NetCatIntents;
})